Código base generado por Chat GPT-4

In [9]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Generación de datos de ejemplo para series de tiempo
# Vamos a crear una serie de tiempo simple para ilustrar el uso del LSTM
def create_dataset(series, time_steps=1):
    X, y = [], []
    for i in range(len(series) - time_steps):
        X.append(series[i:(i + time_steps)])
        y.append(series[i + time_steps])
    return np.array(X), np.array(y)

# Parámetros para la serie de tiempo
data = np.sin(np.linspace(0, 100, 1000))  # Ejemplo de una serie de tiempo sinusoidal
time_steps = 10  # Número de pasos de tiempo para predecir el siguiente valor

# Preparación de los datos
X, y = create_dataset(data, time_steps)
X = X.reshape((X.shape[0], X.shape[1], 1))  # Reshape para ser compatible con LSTM

for i in range(6):
  print("Tiempo i: ",i, "\nX_",i, ": \n", X[i], "  y:", y[i])


Tiempo i:  0 
X_ 0 : 
 [[0.        ]
 [0.09993302]
 [0.19886554]
 [0.29580708]
 [0.3897871 ]
 [0.47986471]
 [0.56513807]
 [0.64475345]
 [0.71791378]
 [0.7838866 ]]   y: 0.8420114062884005
Tiempo i:  1 
X_ 1 : 
 [[0.09993302]
 [0.19886554]
 [0.29580708]
 [0.3897871 ]
 [0.47986471]
 [0.56513807]
 [0.64475345]
 [0.71791378]
 [0.7838866 ]
 [0.84201141]]   y: 0.8917062748888882
Tiempo i:  2 
X_ 2 : 
 [[0.19886554]
 [0.29580708]
 [0.3897871 ]
 [0.47986471]
 [0.56513807]
 [0.64475345]
 [0.71791378]
 [0.7838866 ]
 [0.84201141]
 [0.89170627]]   y: 0.9324736780202824
Tiempo i:  3 
X_ 3 : 
 [[0.29580708]
 [0.3897871 ]
 [0.47986471]
 [0.56513807]
 [0.64475345]
 [0.71791378]
 [0.7838866 ]
 [0.84201141]
 [0.89170627]
 [0.93247368]]   y: 0.9639054660553243
Tiempo i:  4 
X_ 4 : 
 [[0.3897871 ]
 [0.47986471]
 [0.56513807]
 [0.64475345]
 [0.71791378]
 [0.7838866 ]
 [0.84201141]
 [0.89170627]
 [0.93247368]
 [0.96390547]]   y: 0.985686954427788
Tiempo i:  5 
X_ 5 : 
 [[0.47986471]
 [0.56513807]
 [0.644753

In [10]:


# Construcción del modelo LSTM
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(time_steps, 1)))
model.add(Dense(1))

# Compilación del modelo
model.compile(optimizer='adam', loss='mse')

# Entrenamiento del modelo
model.fit(X, y, epochs=200, verbose=1)

# Evaluación del modelo
predicted = model.predict(X)

# Mostrar las primeras 5 predicciones vs. valores reales
for i in range(5):
    print(f'Real: {y[i]}, Predicción: {predicted[i]}')


Epoch 1/200


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


31/31 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.4286
Epoch 2/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1038
Epoch 3/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0516
Epoch 4/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0225
Epoch 5/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0089
Epoch 6/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0018
Epoch 7/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0012
Epoch 8/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7246e-04
Epoch 9/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.3307e-04
Epoch 10/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.0088e-04
Epoch 11/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5332e-04
Epoch 12/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 3.8834e-04
Epoch 13/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.8083e-04
Epoch 14/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3.6206e-04
Epoch 15/200
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - l


### Explicación del código

1. **Generación de datos:** Creamos una serie de tiempo sinusoidal como ejemplo y la transformamos en pares de entrada y salida usando una ventana de tiempo (`time_steps`).

2. **Preparación de los datos:** Reestructuramos los datos para que sean compatibles con la entrada requerida por la capa LSTM, que espera una forma de `(muestras, pasos de tiempo, características)`.

3. **Construcción del modelo:** Creamos un modelo secuencial con una capa LSTM y una capa densa de salida para la predicción.

4. **Entrenamiento del modelo:** Entrenamos el modelo en los datos de la serie de tiempo.

5. **Predicciones:** Realizamos predicciones y mostramos una comparación entre algunos valores reales y los predichos.
